### ISSUE TITLE
@Nullable et al should not be required

### ISSUE THREAD

**Issue by fbiville** [lesaint/damapping#58] opened 2015-01-27 09:12 UTC
Right now in my project:

```
java.lang.NoClassDefFoundError: javax/annotation/Nullable: javax.annotation.Nullable
```

DAMapping should not generate those if they're not available.

**Comment by lesaint** [comment] 2015-02-03 17:04
There is no hard-coded generation of annotation `@Nullable` that I can find.

The DAMapping framework does, however, generate the apply method from Guava's `Function` interface with all the annotations it defines and it does include `javax.annotation.Nullable`.

Is it the problem you are facing ?

If so, here are my thoughts on the matter.

The current principle in the DAMapping framework is that the methods in the generated interfaces/classes are the same as the one defined in the class annotated with `@Mapper` (including annotations on the return type and the parameters). In this case the method is defined by Guava's `Function` and it includes `@Nullable` annotations on the return type and the parameter.

Guava's dependency to the JSR-305 dependency `com.google.code.findbugs:jsr305` artifact is optional. DAMapping's dependency to this artifact is optional too. And the problem is really coming from that dependency being optional. I mean that the same problem could occur with any interface that defines a method with some annotation defined in an optional dependency.

Therefore, it appears that the problem put forward by this issue is larger than just the "`@Nullable` et al" annotations.

However, I won't implement a fix for it. In addition to being complex, this fix will obviously imply performance loss that I don't think is worse it.

DAMapping is providing specific support for Guava's `Function` interface and defines the dependency to the JSR-305 library as optional so it makes sense to fix the issue but the fix will be limited to the `@Nullable` annotation of the `apply` method of Guava's `Function` interface.

**Comment by fbiville** [comment] 2015-02-03 17:12
I updated my initial comment to remove "at runtime".
I think a simple fix would be to not generate @Nullable at all: this way, the code will run for everyone.

**Comment by lesaint** [comment] 2015-02-03 17:17
Not generating `@Nullable` at all would be too bad for people actually having the dependency.

Information is lost that can be used by the IDE or code analyzing tools to detect potential NPEs (when mapper is used out of Guava's `transform` methods).

**Comment by fbiville** [comment] 2015-02-03 17:28
Agreed but seems to me more acceptable than having a `NoClassDefFoundError` for an optional dep.

**Comment by lesaint** [comment] 2015-02-04 13:21
@fbiville, I created an integration test for this issue but I can not reproduce what I thought was your problem.

In a maven module which does **not** have the JSR305 dependency, if I write down the following mapper, no generated code has a `@Nullable` annotation and the module compiles successfully:

```java
@Mapper
public class SimpleMapper implements Function<String, Integer> {

  @Override
  public Integer apply(String input) {
    return null;
  }

}
```

Can you provide a reproducer mapper class, plz ?

**Comment by lesaint** [comment] 2015-02-09 13:59
I thing I figured where the problem is coming from.

Methods generated in MapperFactory interface for each constructor annotated with `@MapperFactory` has a `@Nonnull` on their return type.

Earlier search through the source did not find this one. I stumbled upon it while working on #43. Coming back to this issue when I'm done with #43.

**Comment by lesaint** [comment] 2015-02-09 23:12
the fix for this issue is available in branch 0.6-maintenance.

Is it good for you ?

**Comment by lesaint** [comment] 2015-02-11 23:10
Note: check out this commit on MapStruct for real check of a Type existing in the compiler classpath

* issue : https://github.com/mapstruct/mapstruct/issues/454
* commit : https://github.com/agudian/mapstruct/commit/0c226f8388adfb143593f7072edb90d3a4a76321

**Comment by lesaint** [comment] 2015-02-25 17:21
just committed a change to use `Elements#getTypeElement` instead of `Class.forName()` which is supposed to be a more reliable way to check for a class or interface to be in the classpath of the processor according to the reported issue on MapStruct

**Comment by lesaint** [comment] 2015-02-27 15:20
not waiting for feedback, it looks good to me, issue will be reopened if need be

**Closed by lesaint** 2015-02-27 15:20 UTC
Labels: bug
